name: robloxcloud

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Tailscale installer
      run: |
        cd D:\
        Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-1.66.4-amd64.msi -OutFile tailscale.msi

    - name: Download RobloxCloud
      run: |
        cd D:\
        Invoke-WebRequest https://github.com/RtedPro/RobloxCloud/releases/download/azurebeta/robloxcloudbeta.exe -OutFile RobloxCloud-Beta.exe

    - name: Run Installers
      run: |
        cd D:\
        msiexec /i tailscale.msi
        cmd "RobloxCloud-Beta.exe"
