name: robloxcloud

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Tailscale installer
      run: |
        cd D:\
        Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-1.66.4-amd64.msi -OutFile tailscale.msi

    - name: Download RobloxCloud
      run: |
        cd D:\
        Invoke-WebRequest https://github.com/RtedPro/RobloxCloud/releases/download/azurebeta/robloxcloudbeta.exe -OutFile RobloxCloud-Beta.exe
        Invoke-WebRequest https://github.com/RtedPro/RobloxCloud/releases/download/files/roblox.ova -OutFile roblox.ova

    - name: Run Installers
      run: |
        cd D:\
        dir
        msiexec /i tailscale.msi
        .\RobloxCloud-Beta.exe
        cd MEmu
        cd MEmu
        .\memuc import D:MEmu/MEmu/roblox.ova
        .\memuc import D:MEmu/MEmu/roblox.ova
        .\memuc import D:MEmu/MEmu/roblox.ova
        .\memuc remove --index 0
        .\memuc remove --index 1
        .\python pip.exe install flask
        .\python pip.exe install jsonify
        .\python pip.exe install psutil
