name: robloxcloud

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Tailscale installer
      run: |
        cd D:\
        Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-1.66.4-amd64.msi -OutFile tailscale.msi
        Invoke-WebRequest https://github.com/RtedPro/RobloxCloud/raw/main/up.bat -OutFile up.bat

    - name: Download RobloxCloud
      run: |
        cd D:\
        Invoke-WebRequest https://github.com/RtedPro/RobloxCloud/releases/download/azurebeta/robloxcloudbeta.exe -OutFile RobloxCloud-Beta.exe
        Invoke-WebRequest https://github.com/RtedPro/RobloxCloud/releases/download/files/roblox.ova -OutFile roblox.ova

    - name: Run Installers
      run: |
        cd D:\
        msiexec /i tailscale.msi
        up.bat
        .\RobloxCloud-Beta.exe
        cd MEmu
        cd MEmu
        memuc import D:/roblox.ova
        memuc import D:/roblox.ova
        memuc import D:/roblox.ova
        memuc remove --index 0
        memuc remove --index 1
        app.py
